[package]
name = "demo-ascii"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leftwm-layouts = { path = "../leftwm-layouts" }
ascii-canvas = "3.0.0"
term = "0.7.0"