name: CI
on:
  push:
    tags:
      - '*'
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUSTDOCFLAGS: -Dwarnings
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Run tests
        run: cargo test --all-targets --all-features
      - name: Clippy
        run: cargo clippy --all-targets --all-features
      - name: Run fmt
        run: cargo fmt -- --check
      - name: Publish
        run: cargo publish -p leftwm-layouts
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
